apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::528010887209:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::528010887209:role/eksctl-eksctl-demo-nodegroup-ng-8-NodeInstanceRole-1NCEAP2JB2CV7
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-01T21:10:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1641"
  uid: 9113ae0e-586c-486a-8280-b86a9d3a0d87
